import { Property } from '@/types/property';

export const mockProperties: Property[] = [
  {
    id: 1,
    propertyName: "Luxury Apartment in Downtown",
    propertyType: "Apartment",
    description: "Modern luxury apartment with city views and premium amenities.",
    price: 50000,
    isForRent: true,
    isForSale: false,
    bedrooms: 2,
    bathrooms: 2,
    kitchen: 1,
    floor: 15,
    furnishing: "Attached",
    area: 650,
    city: "Lalitpur",
    state: "Bagmati",
    country: "Nepal",
    address: "Pulchowk, Lalitpur",
    landmark: "Near Pulchowk Campus",
    latitude: 27.6783,
    longitude: 85.3206,
    status: "available",
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-20'),
    imageUrl: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800"
  },
  {
    id: 2,
    propertyName: "Spacious Family Villa",
    propertyType: "Villa",
    description: "Beautiful family villa with garden and parking space.",
    price: 85000,
    isForRent: false,
    isForSale: true,
    bedrooms: 4,
    bathrooms: 3,
    kitchen: 2,
    floor: 2,
    furnishing: "Semi-furnished",
    area: 1200,
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Baluwatar, Kathmandu",
    landmark: "Near Embassy Area",
    latitude: 27.7172,
    longitude: 85.3240,
    status: "available",
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-01-18'),
    imageUrl: "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800"
  },
  {
    id: 3,
    propertyName: "Modern Office Space",
    propertyType: "Commercial",
    description: "Prime office space in business district with modern facilities.",
    price: 120000,
    isForRent: true,
    isForSale: false,
    bedrooms: 0,
    bathrooms: 4,
    kitchen: 1,
    floor: 8,
    furnishing: "Unfurnished",
    area: 2000,
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "New Baneshwor, Kathmandu",
    landmark: "Near World Trade Center",
    latitude: 27.6857,
    longitude: 85.3458,
    status: "available",
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-12'),
    updatedAt: new Date('2024-01-22'),
    imageUrl: "https://images.pexels.com/photos/2467558/pexels-photo-2467558.jpeg?auto=compress&cs=tinysrgb&w=800"
  },
  {
    id: 4,
    propertyName: "Cozy Studio Apartment",
    propertyType: "Studio",
    description: "Perfect studio apartment for young professionals.",
    price: 25000,
    isForRent: true,
    isForSale: false,
    bedrooms: 1,
    bathrooms: 1,
    kitchen: 1,
    floor: 5,
    furnishing: "Fully Furnished",
    area: 400,
    city: "Bhaktapur",
    state: "Bagmati",
    country: "Nepal",
    address: "Dudhpati, Bhaktapur",
    landmark: "Near Khwopa College",
    latitude: 27.6710,
    longitude: 85.4298,
    status: "available",
    isActive: true,
    isFeatured: false,
    createdAt: new Date('2024-01-08'),
    updatedAt: new Date('2024-01-16'),
    imageUrl: "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800"
  },
  {
    id: 5,
    propertyName: "Penthouse with Terrace",
    propertyType: "Penthouse",
    description: "Luxurious penthouse with panoramic city views and terrace.",
    price: 150000,
    isForRent: false,
    isForSale: true,
    bedrooms: 3,
    bathrooms: 3,
    kitchen: 2,
    floor: 20,
    furnishing: "Luxury Furnished",
    area: 1800,
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Durbarmarg, Kathmandu",
    landmark: "Heart of the City",
    latitude: 27.7026,
    longitude: 85.3149,
    status: "available",
    isActive: true,
    isFeatured: true,
    createdAt: new Date('2024-01-05'),
    updatedAt: new Date('2024-01-25'),
    imageUrl: "https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=800"
  }
];