/* /lib/mockData.ts */

export const mockProperties = [
  /* ───────────────────────────── HOSTELS (1‑12) ─────────────────────────── */
  {
    id: 1,
    title: "Modern City‑View Apartment, Pulchowk",
    propertyName: "Modern City‑View Apartment",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Stylish 2‑bedroom flat with exposed brick & carved Newari‑style windows, a short walk from Pulchowk Campus.",
    price: 45_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 2,
    bathrooms: 2,
    kitchen: 1,
    floor: 4,
    furnishing: "Fully Furnished",
    isAttached: true,
    area: 600,
    areaUnit: "sqft",
    city: "Lalitpur",
    state: "Bagmati",
    country: "Nepal",
    address: "Pulchowk‑3, Lalitpur",
    location: "Pulchowk‑3, Lalitpur",
    landmark: "Near IOE Campus",
    latitude: 27.6783,
    longitude: 85.3206,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑10"),
    updatedAt: new Date("2024‑02‑01"),
    ammenities: ["WiFi", "Air Conditioning", "Parking", "Security", "CCTV", "Elevator", "Water Supply", "Backup Electricity"],
    imageUrl:
      "https://images.pexels.com/photos/5575832/pexels-photo-5575832.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 2,
    title: "Ghandruk Mountain Cottage",
    propertyName: "Ghandruk Mountain Cottage",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Stone‑built village home with flower garden and panoramic Annapurna views.",
    price: 1_500_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 3,
    bathrooms: 1,
    kitchen: 1,
    floor: 1,
    furnishing: "Semi‑furnished",
    isAttached: false,
    area: 1_500,
    areaUnit: "sqft",
    city: "Ghandruk",
    state: "Gandaki",
    country: "Nepal",
    address: "Ward‑11, Ghandruk, Kaski",
    location: "Ward‑11, Ghandruk, Kaski",
    landmark: "Close to ACAP Check‑post",
    latitude: 28.3807,
    longitude: 83.8121,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑07"),
    updatedAt: new Date("2024‑02‑20"),
    ammenities: ["WiFi", "Parking", "Garden", "Balcony", "Kitchen Appliances", "TV", "Heating"],
    imageUrl:
      "https://images.pexels.com/photos/3352873/pexels-photo-3352873.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 3,
    title: "Heritage Newari House, Bhaktapur",
    propertyName: "Heritage Newari House",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Centuries‑old brick townhouse restored for boutique homestay in Bhaktapur’s pottery square.",
    price: 60_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 4,
    bathrooms: 2,
    kitchen: 1,
    floor: 3,
    furnishing: "Attached",
    isAttached: true,
    area: 1_200,
    areaUnit: "sqft",
    city: "Bhaktapur",
    state: "Bagmati",
    country: "Nepal",
    address: "Dattatraya Square, Bhaktapur",
    location: "Dattatraya Square, Bhaktapur",
    landmark: "Pottery Square",
    latitude: 27.672,
    longitude: 85.4276,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑25"),
    updatedAt: new Date("2024‑02‑05"),
    ammenities: ["WiFi", "Air Conditioning", "Parking", "Security", "CCTV", "Elevator", "Water Supply", "Backup Electricity", "Internet"],
    imageUrl:
      "https://images.pexels.com/photos/31928624/pexels-photo-31928624.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 4,
    title: "Vibrant Courtyard Home, Kirtipur",
    propertyName: "Purple Courtyard Home",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Colour‑splashed family house with shared courtyard and warm community vibe.",
    price: 28_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 2,
    bathrooms: 1,
    kitchen: 1,
    floor: 2,
    furnishing: "Basic",
    isAttached: false,
    area: 650,
    areaUnit: "sqft",
    city: "Kirtipur",
    state: "Bagmati",
    country: "Nepal",
    address: "Panga, Kirtipur‑6",
    location: "Panga, Kirtipur‑6",
    landmark: "Uma Maheshwar Temple",
    latitude: 27.667,
    longitude: 85.2799,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑02"),
    updatedAt: new Date("2024‑02‑10"),
    ammenities: ["WiFi", "Kitchen Appliances", "TV", "Heating", "Internet"],
    imageUrl:
      "https://images.pexels.com/photos/15040569/pexels-photo-15040569.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 5,
    title: "Brick‑Front Commercial Space, Basantapur",
    propertyName: "Kumari Ghar View Office",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Ground‑floor unit facing Kumari Ghar—ideal for boutique, gallery or café.",
    price: 125_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 0,
    bathrooms: 1,
    kitchen: 0,
    floor: 0,
    furnishing: "Unfurnished",
    isAttached: false,
    area: 900,
    areaUnit: "sqft",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Basantapur, Kathmandu‑22",
    location: "Basantapur, Kathmandu‑22",
    landmark: "Opp. Kumari Ghar",
    latitude: 27.7048,
    longitude: 85.3078,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑28"),
    updatedAt: new Date("2024‑02‑12"),
    imageUrl:
      "https://images.pexels.com/photos/11408377/pexels-photo-11408377.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 6,
    title: "Rustic Homestead, Dhading Besi",
    propertyName: "Rustic Homestead",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Two‑storey mud‑brick farmhouse with livestock shed and terraced fields—perfect for agro‑tourism.",
    price: 950_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 3,
    bathrooms: 1,
    kitchen: 1,
    floor: 2,
    furnishing: "Semi‑furnished",
    isAttached: false,
    area: 2_400,
    areaUnit: "sqft",
    city: "Dhading Besi",
    state: "Bagmati",
    country: "Nepal",
    address: "Ward‑4, Nilkantha‑Nagar",
    location: "Ward‑4, Nilkantha‑Nagar",
    landmark: "Along Prithvi Highway",
    latitude: 27.9122,
    longitude: 84.8892,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑05"),
    updatedAt: new Date("2024‑02‑18"),
    imageUrl:
      "https://images.pexels.com/photos/6016503/pexels-photo-6016503.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 7,
    title: "Traditional Storefront, Bhaktapur Old Town",
    propertyName: "Old Pottery Storefront",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Ground + two floors of timber‑framed shop‑house in heritage lane, ready for craft retail.",
    price: 38_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 0,
    bathrooms: 1,
    kitchen: 0,
    floor: 3,
    furnishing: "Unfurnished",
    isAttached: false,
    area: 700,
    areaUnit: "sqft",
    city: "Bhaktapur",
    state: "Bagmati",
    country: "Nepal",
    address: "Taumadhi Tole, Bhaktapur",
    location: "Taumadhi Tole, Bhaktapur",
    landmark: "Near Nyatapola Temple",
    latitude: 27.6726,
    longitude: 85.4298,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑18"),
    updatedAt: new Date("2024‑02‑03"),
    imageUrl:
      "https://images.pexels.com/photos/31928610/pexels-photo-31928610.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 8,
    title: "Lakeside Cabin, Pokhara‑6",
    propertyName: "Lakeside Cabin",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Cozy wooden cabin just 50 m from Phewa Lake—ideal for digital nomads.",
    price: 55_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 1,
    bathrooms: 1,
    kitchen: 1,
    floor: 1,
    furnishing: "Fully Furnished",
    isAttached: true,
    area: 500,
    areaUnit: "sqft",
    city: "Pokhara",
    state: "Gandaki",
    country: "Nepal",
    address: "Lakeside‑6, Pokhara",
    location: "Lakeside‑6, Pokhara",
    landmark: "Baidam Road",
    latitude: 28.2081,
    longitude: 83.963,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑12"),
    updatedAt: new Date("2024‑02‑01"),
    imageUrl:
      "https://images.pexels.com/photos/20886473/pexels-photo-20886473.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 9,
    title: "Garden Bungalow, Godawari",
    propertyName: "Godawari Garden Bungalow",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Single‑storey house surrounded by botanical garden—peaceful hideaway near Phulchowki trailhead.",
    price: 16_000_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 3,
    bathrooms: 2,
    kitchen: 1,
    floor: 1,
    furnishing: "Semi‑furnished",
    isAttached: true,
    area: 2_000,
    areaUnit: "sqft",
    city: "Godawari",
    state: "Bagmati",
    country: "Nepal",
    address: "Botanical Garden Road",
    location: "Botanical Garden Road",
    landmark: "Godawari Botanical Garden",
    latitude: 27.5916,
    longitude: 85.362,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑15"),
    updatedAt: new Date("2024‑02‑10"),
    imageUrl:
      "https://images.pexels.com/photos/24032619/pexels-photo-24032619.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 10,
    title: "Skyline Office Suite, Lalitpur",
    propertyName: "Modern Walkway Office",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Open‑plan office on 8th floor with floor‑to‑ceiling glass and wooden sky‑bridge access.",
    price: 180_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 0,
    bathrooms: 2,
    kitchen: 1,
    floor: 8,
    furnishing: "Unfurnished",
    isAttached: false,
    area: 2_200,
    areaUnit: "sqft",
    city: "Lalitpur",
    state: "Bagmati",
    country: "Nepal",
    address: "Nakhkhu, Lalitpur‑4",
    location: "Nakhkhu, Lalitpur‑4",
    landmark: "Next to Labim Mall",
    latitude: 27.6641,
    longitude: 85.3174,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑20"),
    updatedAt: new Date("2024‑02‑11"),
    imageUrl:
      "https://images.pexels.com/photos/30874561/pexels-photo-30874561.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 11,
    title: "Hilltop Retreat, Nagarkot",
    propertyName: "Nagarkot Hilltop Retreat",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "Panoramic sunrise villa with wrap‑around deck and 270° Himalaya view.",
    price: 25_000_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 4,
    bathrooms: 3,
    kitchen: 2,
    floor: 2,
    furnishing: "Luxury Furnished",
    isAttached: true,
    area: 3_500,
    areaUnit: "sqft",
    city: "Nagarkot",
    state: "Bagmati",
    country: "Nepal",
    address: "Nagarkot‑view Road",
    location: "Nagarkot‑view Road",
    landmark: "View Tower",
    latitude: 27.7159,
    longitude: 85.52,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑08"),
    updatedAt: new Date("2024‑02‑09"),
    imageUrl:
      "https://images.pexels.com/photos/2969535/pexels-photo-2969535.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 12,
    title: "Peace Pagoda‑View Flat, Pokhara‑15",
    propertyName: "Peace Pagoda‑View Flat",
    propertyType: "Hostel",
    type: "Hostel",
    description:
      "3‑bed apartment overlooking Phewa & World Peace Pagoda—perfect for sunset lovers.",
    price: 65_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 3,
    bathrooms: 2,
    kitchen: 1,
    floor: 5,
    furnishing: "Fully Furnished",
    isAttached: true,
    area: 1_100,
    areaUnit: "sqft",
    city: "Pokhara",
    state: "Gandaki",
    country: "Nepal",
    address: "Damside‑15, Pokhara",
    location: "Damside‑15, Pokhara",
    landmark: "World Peace Pagoda trail",
    latitude: 28.201,
    longitude: 83.958,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑01"),
    updatedAt: new Date("2024‑02‑15"),
    imageUrl:
      "https://images.pexels.com/photos/355561/pexels-photo-355561.jpeg?auto=compress&cs=tinysrgb&w=800",
  },

  /* ───────────────── OTHER PROPERTY TYPES (13‑20) ───────────────── */
  {
    id: 13,
    title: "Brick Row House, Patan Durbar Area",
    propertyName: "Patan Brick Row House",
    propertyType: "Townhouse",
    type: "Townhouse",
    description:
      "Renovated heritage row house with handcrafted windows, steps from Patan Museum.",
    price: 90_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 3,
    bathrooms: 2,
    kitchen: 1,
    floor: 3,
    furnishing: "Attached",
    isAttached: true,
    area: 1_000,
    areaUnit: "sqft",
    city: "Lalitpur",
    state: "Bagmati",
    country: "Nepal",
    address: "Mangal Bazaar, Patan",
    location: "Mangal Bazaar, Patan",
    landmark: "Patan Museum",
    latitude: 27.6768,
    longitude: 85.3143,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑19"),
    updatedAt: new Date("2024‑02‑11"),
    imageUrl:
      "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 14,
    title: "Cozy Study Apartment, Old Baneshwor",
    propertyName: "Cozy Study Apartment",
    propertyType: "Studio",
    type: "Studio",
    description:
      "Compact studio with bright study nook—ideal for students & remote workers.",
    price: 25_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 1,
    bathrooms: 1,
    kitchen: 1,
    floor: 3,
    furnishing: "Fully Furnished",
    isAttached: true,
    area: 450,
    areaUnit: "sqft",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Old Baneshwor, Kathmandu‑10",
    location: "Old Baneshwor, Kathmandu‑10",
    landmark: "Shrine Plaza",
    latitude: 27.6932,
    longitude: 85.3347,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑04"),
    updatedAt: new Date("2024‑02‑14"),
    imageUrl:
      "https://images.pexels.com/photos/2089698/pexels-photo-2089698.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 15,
    title: "Rustic Staircase Home, Kavre",
    propertyName: "Rustic Staircase Home",
    propertyType: "House",
    type: "House",
    description:
      "3‑storey mud‑brick house with carved staircase and orange facade overlooking rice terraces.",
    price: 1_250_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 4,
    bathrooms: 2,
    kitchen: 1,
    floor: 3,
    furnishing: "Basic",
    isAttached: false,
    area: 1_800,
    areaUnit: "sqft",
    city: "Simalchaur",
    state: "Bagmati",
    country: "Nepal",
    address: "Simalchaur Syampati‑3",
    location: "Simalchaur Syampati‑3",
    landmark: "Bethanchok trail",
    latitude: 27.636,
    longitude: 85.622,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑30"),
    updatedAt: new Date("2024‑02‑13"),
    imageUrl:
      "https://images.pexels.com/photos/3938703/pexels-photo-3938703.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 16,
    title: "Penthouse with Terrace, Durbarmarg",
    propertyName: "Durbarmarg Terrace Penthouse",
    propertyType: "Penthouse",
    type: "Penthouse",
    description:
      "Luxury penthouse with covered porch, marble flooring and unobstructed city skyline.",
    price: 32_000_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 3,
    bathrooms: 3,
    kitchen: 2,
    floor: 15,
    furnishing: "Luxury Furnished",
    isAttached: true,
    area: 2_800,
    areaUnit: "sqft",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Durbarmarg, Kathmandu‑1",
    location: "Durbarmarg, Kathmandu‑1",
    landmark: "Opp. Sherpa Mall",
    latitude: 27.709,
    longitude: 85.3157,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑05"),
    updatedAt: new Date("2024‑02‑10"),
    imageUrl:
      "https://images.pexels.com/photos/5500575/pexels-photo-5500575.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 17,
    title: "Green Lawn Villa, Pokhara Suburb",
    propertyName: "Green & White Lawn Villa",
    propertyType: "Villa",
    type: "Villa",
    description:
      "Charming green‑roof villa set on manicured lawn near Begnas Lake.",
    price: 19_000_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 4,
    bathrooms: 3,
    kitchen: 2,
    floor: 2,
    furnishing: "Semi‑furnished",
    isAttached: true,
    area: 3_200,
    areaUnit: "sqft",
    city: "Pokhara",
    state: "Gandaki",
    country: "Nepal",
    address: "Lekhnath‑9, Pokhara",
    location: "Lekhnath‑9, Pokhara",
    landmark: "Begnas Lake entrance",
    latitude: 28.1726,
    longitude: 84.0467,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑06"),
    updatedAt: new Date("2024‑02‑16"),
    imageUrl:
      "https://images.pexels.com/photos/3937685/pexels-photo-3937685.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 18,
    title: "Annapurna‑View City Apartment",
    propertyName: "Annapurna‑View Apartment",
    propertyType: "Apartment",
    type: "Apartment",
    description:
      "Top‑floor 2BHK with balcony overlooking Pokhara city and Annapurna range.",
    price: 48_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 2,
    bathrooms: 2,
    kitchen: 1,
    floor: 7,
    furnishing: "Fully Furnished",
    isAttached: true,
    area: 950,
    areaUnit: "sqft",
    city: "Pokhara",
    state: "Gandaki",
    country: "Nepal",
    address: "Matepani‑10, Pokhara",
    location: "Matepani‑10, Pokhara",
    landmark: "Matepani Gumba",
    latitude: 28.215,
    longitude: 83.995,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑02‑08"),
    updatedAt: new Date("2024‑02‑18"),
    imageUrl:
      "https://images.pexels.com/photos/276671/pexels-photo-276671.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 19,
    title: "Stone‑Step Garden Cottage, Sarangkot",
    propertyName: "Stone‑Step Cottage",
    propertyType: "Cottage",
    type: "Cottage",
    description:
      "Quaint hillside cottage with stone pathway and terraced gardens, perfect for Airbnb.",
    price: 34_000,
    currency: "NPR",
    priceType: "per month",
    isForRent: true,
    isForSale: false,
    bedrooms: 2,
    bathrooms: 1,
    kitchen: 1,
    floor: 1,
    furnishing: "Attached",
    isAttached: true,
    area: 700,
    areaUnit: "sqft",
    city: "Pokhara",
    state: "Gandaki",
    country: "Nepal",
    address: "Sarangkot‑5, Pokhara",
    location: "Sarangkot‑5, Pokhara",
    landmark: "Sarangkot View Point",
    latitude: 28.2367,
    longitude: 83.9689,
    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑22"),
    updatedAt: new Date("2024‑02‑12"),
    imageUrl:
      "https://images.pexels.com/photos/414102/pexels-photo-414102.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 20,
    title: "Fewa Lake Boathouse Cottages",
    propertyName: "Boathouse Cottages",
    propertyType: "Resort",
    type: "Resort",
    description:
      "Twin lakeside cottages with private canoe dock—boutique resort opportunity.",
    price: 45_000_000,
    currency: "NPR",
    priceType: "total",
    isForRent: false,
    isForSale: true,
    bedrooms: 6,
    bathrooms: 6,
    kitchen: 2,
    floor: 1,
    furnishing: "Fully Furnished",
    isAttached: true,
    area: 5_000,
    areaUnit: "sqft",
    city: "Pokhara",
    state: "Gandaki",
    country: "Nepal",
    address: "Lakeside‑4 (Khapaudi), Pokhara",
    location: "Lakeside‑4 (Khapaudi), Pokhara",
    landmark: "Waterfront Resort stretch",
    latitude: 28.2296,
    longitude: 83.9602,
    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,
    createdAt: new Date("2024‑01‑11"),
    updatedAt: new Date("2024‑02‑09"),
    imageUrl:
      "https://images.pexels.com/photos/2179215/pexels-photo-2179215.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
    {
    id: 21,
    title: "Luxury Apartment in Downtown",
    propertyName: "Luxury Apartment in Downtown",
    propertyType: "Apartment",
    type: "Apartment",

    description: "Modern luxury apartment with city views and premium amenities.",
    price: 50000,
    currency: "NPR",
    priceType: "per month",

    isForRent: true,
    isForSale: false,
    bedrooms: 2,
    bathrooms: 2,
    kitchen: 1,
    floor: 15,
    furnishing: "Attached",
    isAttached: true,

    area: 650,
    areaUnit: "m2",
    city: "Lalitpur",
    state: "Bagmati",
    country: "Nepal",
    address: "Pulchowk, Lalitpur",
    
    landmark: "Near Pulchowk Campus",
    latitude: 27.6783,
    longitude: 85.3206,

    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,

    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    ammenities: ["WiFi", "Air Conditioning", "Parking", "Security", "CCTV", "Elevator", "Water Supply", "Backup Electricity"],
    imageUrl:
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 22,
    title: "Spacious Family Villa",
    propertyName: "Spacious Family Villa",
    propertyType: "Villa",
    type: "Villa",

    description: "Beautiful family villa with garden and parking space.",
    price: 85000,
    currency: "NPR",
    priceType: "total",

    isForRent: false,
    isForSale: true,
    bedrooms: 4,
    bathrooms: 3,
    kitchen: 2,
    floor: 2,
    furnishing: "Semi‑furnished",
    isAttached: false,

    area: 1200,
    areaUnit: "m2",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Baluwatar, Kathmandu",
    location: "Baluwatar, Kathmandu",
    landmark: "Near Embassy Area",
    latitude: 27.7172,
    longitude: 85.3240,

    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,

    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-18"),
    ammenities: ["WiFi", "Parking", "Garden", "Balcony", "Kitchen Appliances", "TV", "Heating"],
    imageUrl:
      "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 23,
    title: "Modern Office Space",
    propertyName: "Modern Office Space",
    propertyType: "Commercial",
    type: "Commercial",

    description: "Prime office space in business district with modern facilities.",
    price: 120000,
    currency: "NPR",
    priceType: "per month",

    isForRent: true,
    isForSale: false,
    bedrooms: 0,
    bathrooms: 4,
    kitchen: 1,
    floor: 8,
    furnishing: "Unfurnished",
    isAttached: false,

    area: 2000,
    areaUnit: "m2",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "New Baneshwor, Kathmandu",
    location: "New Baneshwor, Kathmandu",
    landmark: "Near World Trade Center",
    latitude: 27.6857,
    longitude: 85.3458,

    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,

    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-22"),
    ammenities: ["WiFi", "Air Conditioning", "Parking", "Security", "CCTV", "Elevator", "Water Supply", "Backup Electricity", "Internet"],
    imageUrl:
      "https://images.pexels.com/photos/2467558/pexels-photo-2467558.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 24,
    title: "Cozy Studio Apartment",
    propertyName: "Cozy Studio Apartment",
    propertyType: "Studio",
    type: "Studio",

    description: "Perfect studio apartment for young professionals.",
    price: 25000,
    currency: "NPR",
    priceType: "per month",

    isForRent: true,
    isForSale: false,
    bedrooms: 1,
    bathrooms: 1,
    kitchen: 1,
    floor: 5,
    furnishing: "Fully Furnished",
    isAttached: true,

    area: 400,
    areaUnit: "m2",
    city: "Bhaktapur",
    state: "Bagmati",
    country: "Nepal",
    address: "Dudhpati, Bhaktapur",
    location: "Dudhpati, Bhaktapur",
    landmark: "Near Khwopa College",
    latitude: 27.671,
    longitude: 85.4298,

    status: "available",
    isActive: true,
    isFeatured: false,
    isLiked: false,
    views: 0,

    createdAt: new Date("2024-01-08"),
    updatedAt: new Date("2024-01-16"),
    ammenities: ["WiFi", "Kitchen Appliances", "TV", "Heating", "Internet"],
    imageUrl:
      "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
  {
    id: 25,
    title: "Penthouse with Terrace",
    propertyName: "Penthouse with Terrace",
    propertyType: "Penthouse",
    type: "Penthouse",

    description: "Luxurious penthouse with panoramic city views and terrace.",
    price: 150000,
    currency: "NPR",
    priceType: "total",

    isForRent: false,
    isForSale: true,
    bedrooms: 3,
    bathrooms: 3,
    kitchen: 2,
    floor: 20,
    furnishing: "Luxury Furnished",
    isAttached: true,

    area: 1800,
    areaUnit: "m2",
    city: "Kathmandu",
    state: "Bagmati",
    country: "Nepal",
    address: "Durbarmarg, Kathmandu",
    location: "Durbarmarg, Kathmandu",
    landmark: "Heart of the City",
    latitude: 27.7026,
    longitude: 85.3149,

    status: "available",
    isActive: true,
    isFeatured: true,
    isLiked: false,
    views: 0,

    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-25"),
    ammenities: ["WiFi", "Air Conditioning", "Parking", "Security", "CCTV", "Elevator", "Water Supply", "Backup Electricity", "Garden", "Balcony", "Kitchen Appliances", "TV", "Heating", "Internet"],
    imageUrl:
      "https://images.pexels.com/photos/1571453/pexels-photo-1571453.jpeg?auto=compress&cs=tinysrgb&w=800",
  },
];
